/*
 * Drone-Server-API
 *
 * Drone Server API
 *
 * API version: 1.0
 * Contact: drone-derby-eng-team@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_telemetry

import (
	"net/http"
	"time"

	log "github.com/sirupsen/logrus"
)

func Logger(inner http.Handler, name string) http.Handler {

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		inner.ServeHTTP(w, r)
		log.WithFields(log.Fields{
			"Method": r.Method,
			"URI":r.RequestURI,
			"name":name,
			"executionTime":time.Since(start),
		}).Info("HTTP Request Handled")
	})
}
