/*
 * Drone-Telemetry-API
 *
 * Drone Telemetry API
 *
 * API version: 1.0
 * Contact: drone-derby-eng-team@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_telemetry

type CoralStatusAdditionalPropertiesInner struct {

	Key string `json:"key,omitempty"`

	Value string `json:"value,omitempty"`
}

// AssertCoralStatusAdditionalPropertiesInnerRequired checks if the required fields are not zero-ed
func AssertCoralStatusAdditionalPropertiesInnerRequired(obj CoralStatusAdditionalPropertiesInner) error {
	return nil
}

// AssertRecurseCoralStatusAdditionalPropertiesInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CoralStatusAdditionalPropertiesInner (e.g. [][]CoralStatusAdditionalPropertiesInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCoralStatusAdditionalPropertiesInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCoralStatusAdditionalPropertiesInner, ok := obj.(CoralStatusAdditionalPropertiesInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCoralStatusAdditionalPropertiesInnerRequired(aCoralStatusAdditionalPropertiesInner)
	})
}
