/*
 * Drone-Telemetry-API
 *
 * Drone Telemetry API
 *
 * API version: 1.0
 * Contact: drone-derby-eng-team@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_telemetry

type Operations struct {

	Logging []Logs `json:"logging,omitempty"`

	Monitoring string `json:"monitoring,omitempty"`

	SLOs string `json:"SLOs,omitempty"`
}

// AssertOperationsRequired checks if the required fields are not zero-ed
func AssertOperationsRequired(obj Operations) error {
	for _, el := range obj.Logging {
		if err := AssertLogsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseOperationsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Operations (e.g. [][]Operations), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOperationsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOperations, ok := obj.(Operations)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOperationsRequired(aOperations)
	})
}
