/*
 * Drone-Telemetry-API
 *
 * Drone Telemetry API
 *
 * API version: 1.0
 * Contact: drone-derby-eng-team@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_telemetry

import (
	"time"
)

type Logs struct {

	Message string `json:"message,omitempty"`

	Date time.Time `json:"date,omitempty"`

	Level string `json:"level,omitempty"`
}

// AssertLogsRequired checks if the required fields are not zero-ed
func AssertLogsRequired(obj Logs) error {
	return nil
}

// AssertRecurseLogsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Logs (e.g. [][]Logs), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLogsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLogs, ok := obj.(Logs)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLogsRequired(aLogs)
	})
}
