/*
 * Drone-Command-API
 *
 * Drone Command API
 *
 * API version: 1.0
 * Contact: drone-derby-eng-team@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_command

import (
	"context"
	"net/http"
)



// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	DeleteSignId(http.ResponseWriter, *http.Request)
	GetSign(http.ResponseWriter, *http.Request)
	GetSignId(http.ResponseWriter, *http.Request)
	PostControl(http.ResponseWriter, *http.Request)
	PostSignId(http.ResponseWriter, *http.Request)
	PutSignId(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	DeleteSignId(context.Context, string) (ImplResponse, error)
	GetSign(context.Context) (ImplResponse, error)
	GetSignId(context.Context, string) (ImplResponse, error)
	PostControl(context.Context, FlightControl) (ImplResponse, error)
	PostSignId(context.Context, string, SignMapping) (ImplResponse, error)
	PutSignId(context.Context, string, SignMapping) (ImplResponse, error)
}
