/*
 * Drone-Command-API
 *
 * Drone Command API
 *
 * API version: 1.0
 * Contact: drone-derby-eng-team@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_command

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// DeleteSignId - DELETE SignMapping
func (s *DefaultApiService) DeleteSignId(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update DeleteSignId with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteSignId method not implemented")
}

// GetSign - GET all SignMapping object
func (s *DefaultApiService) GetSign(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetSign with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []SignMapping{}) or use other options such as http.Ok ...
	//return Response(200, []SignMapping{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSign method not implemented")
}

// GetSignId - GET SignMapping By ID
func (s *DefaultApiService) GetSignId(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update GetSignId with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, SignMapping{}) or use other options such as http.Ok ...
	//return Response(200, SignMapping{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSignId method not implemented")
}

// PostControl - POST Control order to send to the coral board
func (s *DefaultApiService) PostControl(ctx context.Context, flightControl FlightControl) (ImplResponse, error) {
	// TODO - update PostControl with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostControl method not implemented")
}

// PostSignId - CREATE SignMapping
func (s *DefaultApiService) PostSignId(ctx context.Context, id string, signMapping SignMapping) (ImplResponse, error) {
	// TODO - update PostSignId with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, SignMapping{}) or use other options such as http.Ok ...
	//return Response(201, SignMapping{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostSignId method not implemented")
}

// PutSignId - UPDATE SignMapping
func (s *DefaultApiService) PutSignId(ctx context.Context, id string, signMapping SignMapping) (ImplResponse, error) {
	// TODO - update PutSignId with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, SignMapping{}) or use other options such as http.Ok ...
	//return Response(200, SignMapping{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("PutSignId method not implemented")
}
