/*
 * Drone-Command-API
 *
 * Drone Command API
 *
 * API version: 1.0
 * Contact: drone-derby-eng-team@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_command

type Altitude struct {

	Value int32 `json:"value,omitempty"`

	Way string `json:"way,omitempty"`
}

// AssertAltitudeRequired checks if the required fields are not zero-ed
func AssertAltitudeRequired(obj Altitude) error {
	return nil
}

// AssertRecurseAltitudeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Altitude (e.g. [][]Altitude), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAltitudeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAltitude, ok := obj.(Altitude)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAltitudeRequired(aAltitude)
	})
}
