/*
 * Drone-Server-API
 *
 * Drone Server API
 *
 * API version: 1.0
 * Contact: drone-derby-eng-team@google.com
 */

package main

import (
	"net/http"
	"os"

	telemtry "drone-server-api/internal/telemetry"
	openapi_telemetry "drone-server-api/pkg/openapi-telemetry"

	log "github.com/sirupsen/logrus"
)

func main() {

	//Create the API router generated by openapi-generator-cli
	defaultApiController := openapi_telemetry.NewDefaultApiController(telemtry.NewTelemetryAPIService())
	router := openapi_telemetry.NewRouter(defaultApiController)

	//Enable SWAGGER UI if enabled
	if os.Getenv("SWAGGER_UI_ENABLED") == "true" {
		swHanlder := openapi_telemetry.Logger(http.StripPrefix("/swagger-ui/", http.FileServer(http.Dir("./web/swaggerui/"))),"swagger-ui")
		router.PathPrefix("/swagger-ui").Handler(swHanlder)
		log.Printf("Swagger UI enabled")
	}
	//Start API server
	log.Fatal(http.ListenAndServe(":8080", router))
	log.Printf("Server started")

}
